package gestorStarWarsUI;

import java.io.File;
import java.util.ArrayList;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import starwars.SalvarRecuperar;
import starwars.Articulo;

/**
 * Cuadro de diálogo para crear o bien para modificar un elemento.
 * 
 * @author Carlos Villatoro
 */
public class EditaArticulo extends java.awt.Dialog {
    
    private static ArrayList <Articulo> listaArticulos ;
    private static Articulo unArticulo = null ;
    private static int posicionPasada ;
    
    private static JPanelBackground panel ;  // Panel para mostrar la imagen

    /**
     * Crea nuevo cuadro de diálogo EditaArticulo
     * @param parent    Frame padre del cuadro.
     * @param modal     Modo de apertura de la venta
     * @param listaArticulosRecibida ArrayList con los artículos de la aplicación.
     * @param posicion  Pisición del elemento a modificar o bien -1 si es un alta.
     */
    public EditaArticulo(java.awt.Frame parent, boolean modal, 
            ArrayList <Articulo> listaArticulosRecibida, int posicion)  {
        
        super(parent, modal);
        
        // Obtenemos el arrayList que recibimos desde el formulario invocante
        EditaArticulo.listaArticulos = listaArticulosRecibida ;
        EditaArticulo.posicionPasada = posicion ;
        // En principio, por si se cancela dándole al aspa de la ventana, 
        // inicializamos a null para evitar efectos
        EditaArticulo.unArticulo = null ;
        
        initComponents();
        
        // Crear panel para la imagen del artículo
        panel = new JPanelBackground() ;
        this.add(panel) ;
        panel.setLocation(265, 130);
        // Tamaño del panel para mostrar la imagen
        panel.setSize(220, 190);
            
        // Si es una modificación cargamos el formulario
        if (posicion != -1) {
            this.setTitle("Modificar artículo");
            
            Articulo temporal = (Articulo) listaArticulosRecibida.get(posicion) ;
                             
            this.jTextCodigo.setText(temporal.getCodigo() + "") ;
            this.jTextDescripcion.setText(temporal.getDescripcion()) ;
            this.jComboPaises.setSelectedItem(temporal.getPais());
            this.jSpinnerAnnio.setValue(temporal.getAnnio());
            this.jCheckDesmontable.setSelected(temporal.isDesmontable());
            this.jSpinnerAlto.setValue(temporal.getAlto());
            this.jSpinnerAncho.setValue(temporal.getAncho());
            this.jSpinnerPrecio.setValue(temporal.getPrecio());
            this.jTextNombreArchivoImagen.setText(temporal.getNombreImagen());
            
            //Ecribe la ruta del fichero seleccionado en el campo de texto
            File archivo = new File (temporal.getNombreImagen());
            // Actualizar ña imagen del panel con la seleccionada
            panel.setBackground(archivo.getAbsolutePath()) ;  
            panel.setVisible(true);
            panel.repaint(); 
                    
            
        } else {
            unArticulo = null ;
            // En el caso de un alta el código será el último más uno
            String codigo = Articulo.getCodigoUltimoElemento() + 1 + "" ;
            this.jTextCodigo.setText(codigo);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelCodigo = new javax.swing.JLabel();
        jLabelDescripcion = new javax.swing.JLabel();
        jCheckDesmontable = new javax.swing.JCheckBox();
        jPanel1 = new javax.swing.JPanel();
        jLabelAlto = new javax.swing.JLabel();
        jLabelAncho = new javax.swing.JLabel();
        jSpinnerAlto = new javax.swing.JSpinner();
        jSpinnerAncho = new javax.swing.JSpinner();
        jBotonAceptar = new javax.swing.JButton();
        jBotonCancelar = new javax.swing.JButton();
        jTextDescripcion = new javax.swing.JTextField();
        jLabelValorFacial = new javax.swing.JLabel();
        jLabelPais = new javax.swing.JLabel();
        jTextCodigo = new javax.swing.JTextField();
        jComboPaises = new javax.swing.JComboBox();
        jSpinnerAnnio = new javax.swing.JSpinner();
        jLabelAnnio = new javax.swing.JLabel();
        jSpinnerPrecio = new javax.swing.JSpinner();
        jBotonSeleccionarImagen = new javax.swing.JButton();
        jTextNombreArchivoImagen = new javax.swing.JTextField();

        setBackground(new java.awt.Color(204, 204, 204));
        setModal(true);
        setResizable(false);
        setTitle("Editar artículo");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });
        setLayout(null);

        jLabelCodigo.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabelCodigo.setText("Código:");
        add(jLabelCodigo);
        jLabelCodigo.setBounds(20, 40, 50, 14);

        jLabelDescripcion.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabelDescripcion.setText("Descripción:");
        add(jLabelDescripcion);
        jLabelDescripcion.setBounds(20, 80, 70, 14);

        jCheckDesmontable.setBackground(new java.awt.Color(204, 204, 204));
        jCheckDesmontable.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jCheckDesmontable.setText("Desmontable");
        jCheckDesmontable.setToolTipText("");
        jCheckDesmontable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckDesmontableActionPerformed(evt);
            }
        });
        add(jCheckDesmontable);
        jCheckDesmontable.setBounds(20, 250, 120, 23);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Medidas"));
        jPanel1.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jPanel1.setName("panelMedidas"); // NOI18N

        jLabelAlto.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabelAlto.setText("Alto");
        jLabelAlto.setName("jLabelAlto"); // NOI18N

        jLabelAncho.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabelAncho.setText("Ancho");
        jLabelAncho.setName("jLabelAncho"); // NOI18N

        jSpinnerAlto.setModel(new javax.swing.SpinnerNumberModel(1, 1, 100, 1));

        jSpinnerAncho.setModel(new javax.swing.SpinnerNumberModel(1, 1, 100, 1));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(jLabelAlto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSpinnerAlto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jLabelAncho)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(jSpinnerAncho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelAlto)
                    .addComponent(jSpinnerAlto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSpinnerAncho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelAncho))
                .addGap(55, 55, 55))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabelAlto, jLabelAncho, jSpinnerAlto, jSpinnerAncho});

        add(jPanel1);
        jPanel1.setBounds(260, 30, 230, 80);

        jBotonAceptar.setMnemonic('A');
        jBotonAceptar.setText("Aceptar");
        jBotonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBotonAceptarActionPerformed(evt);
            }
        });
        add(jBotonAceptar);
        jBotonAceptar.setBounds(20, 350, 71, 23);

        jBotonCancelar.setMnemonic('C');
        jBotonCancelar.setText("Cancelar");
        jBotonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBotonCancelarActionPerformed(evt);
            }
        });
        add(jBotonCancelar);
        jBotonCancelar.setBounds(150, 350, 80, 23);
        add(jTextDescripcion);
        jTextDescripcion.setBounds(90, 70, 140, 30);

        jLabelValorFacial.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelValorFacial.setText("Precio:");
        add(jLabelValorFacial);
        jLabelValorFacial.setBounds(20, 120, 60, 14);
        jLabelValorFacial.getAccessibleContext().setAccessibleName("Pecio:");

        jLabelPais.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelPais.setText("Fabricado en:");
        add(jLabelPais);
        jLabelPais.setBounds(20, 180, 90, 14);
        jLabelPais.getAccessibleContext().setAccessibleName("Fabricado en;");

        jTextCodigo.setEditable(false);
        jTextCodigo.setEnabled(false);
        jTextCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextCodigoActionPerformed(evt);
            }
        });
        add(jTextCodigo);
        jTextCodigo.setBounds(90, 30, 140, 30);

        jComboPaises.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jComboPaises.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Alemania", "Bélgica", "China", "Cuba", "España", "E.E.U.U.", "Francia", "India", "Inglaterra", "Turquía", "Venezuela", "Vietnam" }));
        add(jComboPaises);
        jComboPaises.setBounds(130, 170, 100, 30);

        jSpinnerAnnio.setModel(new javax.swing.SpinnerNumberModel(2015, 1977, null, 1));
        add(jSpinnerAnnio);
        jSpinnerAnnio.setBounds(160, 210, 70, 30);

        jLabelAnnio.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabelAnnio.setText("Año de lanzamiento:");
        add(jLabelAnnio);
        jLabelAnnio.setBounds(20, 220, 120, 14);

        jSpinnerPrecio.setModel(new javax.swing.SpinnerNumberModel(0.01f, 0.01f, null, 0.01f));
        add(jSpinnerPrecio);
        jSpinnerPrecio.setBounds(90, 110, 140, 30);

        jBotonSeleccionarImagen.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jBotonSeleccionarImagen.setText("Seleccionar imagen");
        jBotonSeleccionarImagen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBotonSeleccionarImagenActionPerformed(evt);
            }
        });
        add(jBotonSeleccionarImagen);
        jBotonSeleccionarImagen.setBounds(20, 280, 210, 23);
        add(jTextNombreArchivoImagen);
        jTextNombreArchivoImagen.setBounds(20, 310, 210, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Closes the dialog
     */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog

    private void jCheckDesmontableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckDesmontableActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckDesmontableActionPerformed

    private void jTextCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextCodigoActionPerformed

    private void jBotonAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBotonAceptarActionPerformed
        // Descripción del artículo                
        String nombre = jTextDescripcion.getText().trim() ;
        if (nombre.isEmpty())
            JOptionPane.showMessageDialog(null,
                        "La descripción del artículo no puede estar vacía",
                        "Atención",
                        JOptionPane.ERROR_MESSAGE); 
        else {
            
            boolean desmontable = false ;
            if (this.jCheckDesmontable.isSelected())
                desmontable = true ;
            
            int posicion = -1 ;
            
            // Si es un alta
            if (posicionPasada == -1) {

                // comprobamos que el código no exista ya en el ArrayList
                posicion = SalvarRecuperar.getPosicionEnLista(listaArticulos, 
                        Integer.parseInt(jTextCodigo.getText())) ;

                // Si es un alta y ya existe el código
                if (posicion != -1) {
                    // si devuelve algo que no sea -1 es que ese código ya existe.
                    JOptionPane.showMessageDialog(null,
                            "Ya existe un artículo con ese código en la aplicación",
                            "Atención",
                            JOptionPane.INFORMATION_MESSAGE); 
                } else {
                    // Crear el objeto artículo
                    EditaArticulo.unArticulo = new Articulo(jTextDescripcion.getText(),
                            (int) jSpinnerAnnio.getValue(),
                            (String) jComboPaises.getSelectedItem(), 
                            (float) jSpinnerPrecio.getValue(),        
                            desmontable, (int) this.jSpinnerAlto.getValue(),
                            (int) this.jSpinnerAncho.getValue(),
                            this.jTextNombreArchivoImagen.getText()) ;  
                }
              // Si es una modificación    
            } else {

                // Obtener el valor del alto
                String valorAlto = jSpinnerAlto.getModel().getValue().toString() ;
                float valor = Float.valueOf(valorAlto) ;
                int elAlto = (int) valor ;

                // Obtener el valor del ancho
                String miAncho = jSpinnerAncho.getModel().getValue().toString() ;
                float valorAncho = Float.valueOf(miAncho) ;
                int elAncho = (int) valorAncho ;

                EditaArticulo.unArticulo = (Articulo) listaArticulos.get(EditaArticulo.posicionPasada) ;
                EditaArticulo.unArticulo.setDescripcion(jTextDescripcion.getText()) ;
                EditaArticulo.unArticulo.setPais((String) jComboPaises.getSelectedItem());
                EditaArticulo.unArticulo.setPrecio((float) jSpinnerPrecio.getValue()) ;         
                EditaArticulo.unArticulo.setAnnio((int) jSpinnerAnnio.getValue()) ;
                EditaArticulo.unArticulo.setAlto(elAlto) ;  
                EditaArticulo.unArticulo.setDesmontable(this.jCheckDesmontable.isSelected()) ;
                EditaArticulo.unArticulo.setAncho(elAncho) ;
                EditaArticulo.unArticulo.setNombreImagen(jTextNombreArchivoImagen.getText());
            }

            // Ocultamos este formulario para devolver  el control al principal
            this.setVisible(false);
        }       
        
    }//GEN-LAST:event_jBotonAceptarActionPerformed

    private void jBotonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBotonCancelarActionPerformed

        // Ocultamos este formulario para devolver  el control al principal
        this.setVisible(false);
    }//GEN-LAST:event_jBotonCancelarActionPerformed

    private void jBotonSeleccionarImagenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBotonSeleccionarImagenActionPerformed
       
        //Creamos el objeto JFileChooser
        JFileChooser filechooser = new JFileChooser();
        
        FileNameExtensionFilter filter = new FileNameExtensionFilter("JPG & GIF & PNG", "jpg", "gif", "png");
        filechooser.setFileFilter(filter);
        
        //Abrimos la ventana, guardamos la opcion seleccionada por el usuario
        int seleccion = filechooser.showOpenDialog(this);
 
        //Si el usuario, pincha en aceptar
        if(seleccion == JFileChooser.APPROVE_OPTION){
             
            //Seleccionamos el fichero
            File fichero = filechooser.getSelectedFile();
 
            //Ecribe la ruta del fichero seleccionado en el campo de texto
            jTextNombreArchivoImagen.setText(fichero.getAbsolutePath());
                      
            // Actualizar ña imagen del panel con la seleccionada
            panel.setBackground(fichero.getAbsolutePath());
            panel.setVisible(true);
            panel.repaint();  
        }
    }//GEN-LAST:event_jBotonSeleccionarImagenActionPerformed

    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBotonAceptar;
    private javax.swing.JButton jBotonCancelar;
    private javax.swing.JButton jBotonSeleccionarImagen;
    private javax.swing.JCheckBox jCheckDesmontable;
    private javax.swing.JComboBox jComboPaises;
    private javax.swing.JLabel jLabelAlto;
    private javax.swing.JLabel jLabelAncho;
    private javax.swing.JLabel jLabelAnnio;
    private javax.swing.JLabel jLabelCodigo;
    private javax.swing.JLabel jLabelDescripcion;
    private javax.swing.JLabel jLabelPais;
    private javax.swing.JLabel jLabelValorFacial;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSpinner jSpinnerAlto;
    private javax.swing.JSpinner jSpinnerAncho;
    private javax.swing.JSpinner jSpinnerAnnio;
    private javax.swing.JSpinner jSpinnerPrecio;
    private javax.swing.JTextField jTextCodigo;
    private javax.swing.JTextField jTextDescripcion;
    private javax.swing.JTextField jTextNombreArchivoImagen;
    // End of variables declaration//GEN-END:variables

    /**
     * Retornar el artículo para que se recoja desde el formulario que llama a éste.
     * @return El objeto elemento.
     */
    protected Articulo getArticulo() {
        return EditaArticulo.unArticulo ;
    }
}
