package gestorStarWarsUI;

import java.util.ArrayList;
import java.util.Collections;
import javax.swing.JOptionPane;
import starwars.ComparadorDescripcionAscendente;
import starwars.ComparadorDescripcionDescendente;
import starwars.ComparadorPrecio;
import starwars.Articulo;

/**
 * Clase para gestión gráfica del listado de sellos contenidos en el array 
 *
 * @author Carlos Villatoro
 * @version 1.1 01/01/2018 (PROG10)
 */
public class ListarArticulos extends javax.swing.JDialog {
    
    private static ArrayList <Articulo> lista; //declaramos un ArrayList para vuelco de datos
    
    /**
     * Contructor de la clase ListarArticulos
     * 
     * @since version 2.0 13/04/2014 (PROG10)
     * @param parent frame desde donde se crea el objeto
     * @param modal modo de arranque (true o false)
     * @param listaArticulos Lista con los objetos sello
     */
    public ListarArticulos(java.awt.Frame parent, boolean modal,
            ArrayList <Articulo> listaArticulos) {
        
        super(parent, modal);
        initComponents();
        // Desactivar la edición del total visualizado a pie de pantalla
        this.totalArticulos.setEditable(false); 
          
        // Referencia a la lista para obtener los sello
        ListarArticulos.lista = listaArticulos ;  
        Collections.sort(lista, new ComparadorDescripcionAscendente());
        
        int conta ;
        int tamano =  ListarArticulos.lista.size() ;
        final String vect[] = new String[tamano];
        for (conta = 0; conta < tamano; conta++ ) {
            vect[conta] = ListarArticulos.lista.get(conta).getCodigo() + " -- " + 
                    ListarArticulos.lista.get(conta).getDescripcion() + " -- " + 
                    ListarArticulos.lista.get(conta).getPrecio() + " -- " + 
                    ListarArticulos.lista.get(conta).getPais() ;
        }
        
        this.jListaArticulos.setModel(new javax.swing.AbstractListModel() {
            String[] strings = vect ;  //{ "Prueba", "Item 2", "Item 3", "Item 4", "Item 5" };
            @Override
            public int getSize() { 
                return strings.length; 
            }
            @Override
            public Object getElementAt(int i) {
                return strings[i]; 
            }
        });
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup4 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListaArticulos = new javax.swing.JList();
        jLabel1 = new javax.swing.JLabel();
        radioDescripAZ = new javax.swing.JRadioButton();
        radioDescripZA = new javax.swing.JRadioButton();
        radioPrecio = new javax.swing.JRadioButton();
        botonVerInfo = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabelTotal = new javax.swing.JLabel();
        totalArticulos = new javax.swing.JTextField();
        botonCerrarListado = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Artículos (Código -- Descripción -- Precio -- País fabricación)"));
        jPanel1.setInheritsPopupMenu(true);

        jScrollPane1.setViewportBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jListaArticulos.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jListaArticulos.setName(""); // NOI18N
        jScrollPane1.setViewportView(jListaArticulos);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel1.setText("Ordenar por:");

        buttonGroup4.add(radioDescripAZ);
        radioDescripAZ.setSelected(true);
        radioDescripAZ.setText("Descripción (A-Z)");
        radioDescripAZ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioDescripAZActionPerformed(evt);
            }
        });

        buttonGroup4.add(radioDescripZA);
        radioDescripZA.setText("Descripción (Z-A)");
        radioDescripZA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioDescripZAActionPerformed(evt);
            }
        });

        buttonGroup4.add(radioPrecio);
        radioPrecio.setText("Precio");
        radioPrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioPrecioActionPerformed(evt);
            }
        });

        botonVerInfo.setText("Ver Información");
        botonVerInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVerInfoActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Totales", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 11))); // NOI18N

        jLabelTotal.setText("Número total de artículos:");

        totalArticulos.setText(String.valueOf(gestorStarWarsUI.Principal.getListaArticulos().size()));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTotal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(totalArticulos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTotal)
                    .addComponent(totalArticulos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(68, 68, 68))
        );

        jLabelTotal.getAccessibleContext().setAccessibleName("Número total de artículos:");

        botonCerrarListado.setText("Cerrar Listado");
        botonCerrarListado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCerrarListadoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(103, 103, 103)
                                .addComponent(botonCerrarListado))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(radioDescripAZ)
                                .addGap(18, 18, 18)
                                .addComponent(radioDescripZA)
                                .addGap(18, 18, 18)
                                .addComponent(radioPrecio))
                            .addComponent(jLabel1)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(botonVerInfo)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 588, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 20, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioDescripAZ)
                    .addComponent(radioDescripZA)
                    .addComponent(radioPrecio)
                    .addComponent(botonVerInfo))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botonCerrarListado)
                        .addGap(39, 39, 39))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel1.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonVerInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVerInfoActionPerformed
        //Si pulsamos Ver informaciÃ³n, se muestra el trabajador seleccionado en 
        //una ventana
        if (this.jListaArticulos.getSelectedIndex()>=0){
            JOptionPane.showMessageDialog(null,  ListarArticulos.lista.get(this.jListaArticulos.getSelectedIndex()), 
                    "Datos", JOptionPane.INFORMATION_MESSAGE);
        }else{ //si no se ha seleccionado ningÃºn trabajador, mensaje de error
            JOptionPane.showMessageDialog(null, "No hay ningún sello seleccionado.", 
                    "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_botonVerInfoActionPerformed

    private void botonCerrarListadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCerrarListadoActionPerformed
        this.setVisible(false); //si se pulsa Cerrar, devolvemos el control al frame
    }//GEN-LAST:event_botonCerrarListadoActionPerformed

    private void radioPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioPrecioActionPerformed
        int conta ;
        Collections.sort(ListarArticulos.lista, new ComparadorPrecio());
        int tamano =  ListarArticulos.lista.size() ;
        final String vect[] = new String[tamano];  
        for (conta = 0; conta < tamano; conta++ ) {
            vect[conta] = ListarArticulos.lista.get(conta).getCodigo() + " -- " +
                    ListarArticulos.lista.get(conta).getDescripcion()+ " -- " + 
                    ListarArticulos.lista.get(conta).getPrecio() + " -- " + 
                    ListarArticulos.lista.get(conta).getPais() ;
        }
        
        this.jListaArticulos.setModel(new javax.swing.AbstractListModel() {
            String[] strings = vect ;  
            
            @Override
            public int getSize() { 
                return strings.length; 
            }
            
            @Override
            public Object getElementAt(int i) {
                return strings[i]; 
            }
        });
    }//GEN-LAST:event_radioPrecioActionPerformed

    private void radioDescripZAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioDescripZAActionPerformed
        //si se marca ordenaciÃ³n Z-A, actualizamos
        int conta ;
        Collections.sort(ListarArticulos.lista, new ComparadorDescripcionDescendente());
        int tamano = lista.size() ;
        final String vect[] = new String[tamano];  
        
        for (conta = 0; conta < tamano; conta++ ) {
            vect[conta] = ListarArticulos.lista.get(conta).getCodigo() + " -- " +
                    ListarArticulos.lista.get(conta).getDescripcion()+ " -- " + 
                    ListarArticulos.lista.get(conta).getPrecio() + " -- " + 
                    ListarArticulos.lista.get(conta).getPais() ;
        }
        
        jListaArticulos.setModel(new javax.swing.AbstractListModel() {
            String[] strings = vect ;  
            
            @Override
            public int getSize() { 
                return strings.length; 
            }
            
            @Override
            public Object getElementAt(int i) {
                return strings[i]; 
            }
        });  
    }//GEN-LAST:event_radioDescripZAActionPerformed

    private void radioDescripAZActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioDescripAZActionPerformed
         
        int conta;
        Collections.sort(ListarArticulos.lista, new ComparadorDescripcionAscendente());
        int tamano = lista.size() ;
      
        final String vect[] = new String[tamano];  
        for (conta = 0; conta < tamano; conta++ ) {
               vect[conta] = ListarArticulos.lista.get(conta).getCodigo() + " -- " +
                    ListarArticulos.lista.get(conta).getDescripcion()+ " -- " + 
                    ListarArticulos.lista.get(conta).getPrecio() + " -- " + 
                    ListarArticulos.lista.get(conta).getPais() ;
        }
        
        jListaArticulos.setModel(new javax.swing.AbstractListModel() {
            String[] strings = vect ;  
            
            @Override
            public int getSize() { 
                return strings.length; 
            }
           
            @Override
            public Object getElementAt(int i) {
                return strings[i]; 
            }
        });  
    }//GEN-LAST:event_radioDescripAZActionPerformed

    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonCerrarListado;
    private javax.swing.JButton botonVerInfo;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelTotal;
    private javax.swing.JList jListaArticulos;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton radioDescripAZ;
    private javax.swing.JRadioButton radioDescripZA;
    private javax.swing.JRadioButton radioPrecio;
    private javax.swing.JTextField totalArticulos;
    // End of variables declaration//GEN-END:variables
}
